---
defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint | tee /tmp/lint.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Test" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/lint.log)\`\`\`" \
            notify-job-failure.sh

  prod:
    <<: *defaults
    steps:
      - checkout
      - run: activate-gcloud-account.sh
      - run: make | tee /tmp/deploy.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Deploy" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/deploy.log)\`\`\`" \
            notify-job-failure.sh
      - run: |
          TYPE="Deploy" \
          EXTRA_TEXT="\`\`\`$(make history)\`\`\`" \
          notify-job-success.sh

  backup:
    <<: *defaults
    steps:
      - checkout
      - run: activate-gcloud-account.sh
      - run: make backup | tee /tmp/backup.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Deploy" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/backup.log)\`\`\`" \
            notify-job-failure.sh

workflows:
  version: 2
  commit:
    jobs:
      - lint:
          context: org-global
      - prod:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - master
  backup-tag:
    jobs:
      - backup:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^backup.*/
  nightly:
    jobs:
      - backup:
          context: org-global
    triggers:
      - schedule:
          cron: "23 2 * * *"
          filters:
            branches:
              only:
                - master
